### PR TITLE
Various fixes, especially for the MegaDrive and PC-Engine emulation on PSVita

### PR DESCRIPTION
**Pull request by SoftechSoftware**

### CODE REVIEW

**Comment by rsn8887** [comment]
Note I have merged this into master at my fork, and already cleaned up the merge to conform to style (comments, spaces/tabs etc.)

Tested and seems to work fine.

I also put a commit based on SoftechSoftware's patch to my fork of libcross2d to fix that issue with multiple timer objects (but without changing inheritance).

**Comment by SoftechSoftware** [comment]
@rsn8887 
I'm quite ready to send the fix for PC-Engine emulator making it fully functional in PFBA on PSVita.

**Comment by rsn8887** [comment]
Again, this is now rebased already into my master branch at my fork www.github.com/rsn8887/pfba

**Comment by Cpasjuste** [comment]
Hi guys !

First, thanks for all your work, and sorry for the late reply, i'm busy :)

I'm actually doing a big refactor of libcross2d. It's now more object oriented, with some helpers for ui elements etc.. it's now based on sfml transformation/matrix code which allow cool things like parenting, relative transform modification (rotation, scale etc) of all "widgets" (lines, rects, textures, fonts..). It also run or almost run on linux, vita, ps3, 3ds :
https://github.com/Cpasjuste/libcross2d/blob/sfml_test/test/main.cpp

PFBA ui does need big changes for that, so i'm actually rewriting it, and in the same time improve the style :
http://files.mydedibox.fr/files/Dev/psp2/pfba/screen1_new.png

So i'm not sure if the ui changes in this commits should be merged (i think i should i will), but they will be lost in my next release (i hope i can do that soon, but i'm loosing some time as i received a switch on working on porting libcross2d on it..). 

For the filenames fixes, this is really cool. I didn't had the time to take a closer look but i wonder if those changes would be possible in the "PFBA" source code, not in the vanilla "FBA" sources (the "src" folder) ? For now the FBA sources are untouched if i remember correctly, so anyone can easily update fba sources without breaking PFBA. 

I'm not sure the way to go, i think it could be : 
- take a look if we can move filenames changes from vanilla fba to pfba rom/filename handling, 
- merge all the changes
- when i'm ready i overwrite the branch, we would then need to re-implement you ui changes (which should be even easier with the new cross2d lib).

**Comment by SoftechSoftware** [comment]
@Cpasjuste 
Since you're going to rewrite a lot of code I think it's better you first integrate the pull request(s) then proceed with the mass modifications. But if it's too late for that I still think it would be better if you take care of integrating my pull request(s) after you finished with your mass modifications.
It's not my intention to become an official PFBA manteiner, simply I gifted to my brother a PS Vita for his birthday and found that the excellent PFBA had some bugs and some emulators not working, then I decided to dig into the code to see if it was possible to fix some of them.
If it can help, in the future I could just send you the modified files. Just let me know an email address...

**Comment by rsn8887** [comment]
Since I have already incorporated the Softech changes in my master, I think I will put up an "intermediate" mod release 1.16 with 
Changelog:
- update to latest fba version 0.2.97.42
- fixes for console games (SofttechSoftware)


and then the big new release could be 2.0 or something :)

**Comment by Cpasjuste** [comment]
Yes of course, @rsn8887. You can release whatever you want !

**Comment by Cpasjuste** [comment]
There won't be a lot of changes in my changes for the end user anyway..

**Comment by rsn8887** [comment]
Ok I did it. Btw I made a PR for the (old) Libcross2D. It might reduce input lag and can't hurt to call SDL_JoystickUpdate() explicitly every frame. This certainly works well in UAE4All2.

**Pull request closed without merging**
